import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'

export const maxDuration = 60

async function tryFalRecraft(prompt: string, style: string): Promise<string | null> {
  const key = process.env.FAL_KEY
  if (!key) return null
  try {
    const res = await fetch('https://fal.run/fal-ai/recraft/v3/text-to-image', {
      method: 'POST',
      headers: { 'Authorization': 'Key ' + key, 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt, image_size: { width: 1024, height: 1024 }, style, num_images: 1 }),
    })
    if (!res.ok) {
      console.error('fal error:', res.status, (await res.text()).slice(0, 100))
      return null
    }
    const data = await res.json()
    return data.images?.[0]?.url || null
  } catch (e) {
    console.error('fal exception:', String(e))
    return null
  }
}

async function generateSVGLogo(
  anthropic: Anthropic,
  concept: { style?: string; description?: string },
  colors: Array<{ hex: string; name: string }>,
  businessName: string
): Promise<string> {
  const primary = colors[0]?.hex || '#1D9E75'
  const secondary = colors[1]?.hex || '#2C5F2E'
  const accent = colors[2]?.hex || '#F4A261'

  const prompt = `Design a professional SVG logo icon for "${businessName}".
Style: ${concept.style || 'Minimalist'}
Design concept: ${concept.description || 'clean geometric mark'}
Brand colors: primary ${primary}, secondary ${secondary}, accent ${accent}
Canvas: viewBox="0 0 400 400"

Rules:
- NO text or letters, pure icon/symbol only
- Use ONLY the brand colors listed above plus white #FFFFFF
- Clean vector paths, no blur, no shadows, no gradients
- Centered, 40px padding from edges
- The icon must VISUALLY represent the concept description

Return ONLY the SVG code starting with <svg and ending with </svg>. Nothing else.`

  const res = await anthropic.messages.create({
    model: 'claude-sonnet-4-5-20250929',
    max_tokens: 3000,
    messages: [{ role: 'user', content: prompt }]
  })
  const text = res.content[0].type === 'text' ? res.content[0].text.trim() : ''
  const match = text.match(/<svg[\s\S]*<\/svg>/i)
  if (match) return match[0]

  // Minimal fallback
  return `<svg viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg">
  <rect width="400" height="400" fill="white"/>
  <circle cx="200" cy="200" r="120" fill="${primary}" opacity="0.15"/>
  <circle cx="200" cy="200" r="80" fill="${primary}"/>
  <circle cx="200" cy="200" r="50" fill="white"/>
  <circle cx="200" cy="200" r="30" fill="${accent}"/>
</svg>`
}

// Build fal prompt from AI concept description
function buildFalPrompt(
  concept: { style?: string; description?: string },
  businessName: string,
  colors: Array<{ hex: string; name: string }>,
  industry: string
): string {
  const name = businessName.split(',')[0].trim()
  const primary = colors[0]?.hex || '#1D9E75'
  const desc = concept.description || ''
  const style = concept.style || 'Minimalist'

  // Use the AI's actual description as the core of the prompt
  return `${style} logo icon for "${name}" brand. ${desc} Brand color ${primary}. ${industry} industry. Professional logo, clean vector, white background, no text, no words, no letters`
}

export async function POST(request: Request) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { brand_kit_id } = await request.json()
    const adminClient = createAdminClient()
    const { data: kit } = await adminClient
      .from('brand_kits')
      .select('business_name, visual_data, strategy_data')
      .eq('id', brand_kit_id).single()
    if (!kit) return NextResponse.json({ error: 'Not found' }, { status: 404 })

    const visual = (kit.visual_data || {}) as Record<string, unknown>
    const colors = (visual.colors as Array<{ hex: string; name: string }>) || []

    // Get logo_concepts from visual_data (generated by AI with specific descriptions)
    const concepts = (visual.logo_concepts as Array<{ style?: string; description?: string }>) || []
    // Ensure exactly 3 concepts
    while (concepts.length < 3) {
      concepts.push([
        { style: 'Wordmark', description: 'Clean typographic logo with brand name in bold modern font, simple geometric accent' },
        { style: 'Lettermark', description: 'Stylized initials monogram with geometric shapes, modern minimal design' },
        { style: 'Combination Mark', description: 'Icon symbol combined with brand name, professional and memorable' },
      ][concepts.length] || { style: 'Minimalist', description: 'Clean geometric icon mark' })
    }

    // Detect industry from business name / strategy
    const strategy = (kit.strategy_data || {}) as Record<string, unknown>
    const industry = String((strategy as Record<string, unknown>).unique_value_proposition || kit.business_name).slice(0, 30)

    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

    // fal.ai styles - all valid for Recraft V3
    const falStyles = [
      'vector_illustration',
      'vector_illustration/line_art',
      'vector_illustration'
    ]

    const logoUrls: string[] = []
    const logoSvgs: string[] = []
    const usedFal: boolean[] = []
    const promptsUsed: string[] = []

    for (let i = 0; i < 3; i++) {
      const concept = concepts[i]
      // Build prompt FROM the AI's concept description
      const falPrompt = buildFalPrompt(concept, kit.business_name, colors, industry)
      promptsUsed.push(falPrompt)
      console.log(`Logo ${i+1} prompt: ${falPrompt.slice(0,80)}...`)

      // Try fal.ai
      const falUrl = await tryFalRecraft(falPrompt, falStyles[i])
      if (falUrl) {
        logoUrls.push(falUrl)
        logoSvgs.push('')
        usedFal.push(true)
        console.log(`Logo ${i+1}: fal.ai OK`)
      } else {
        // Fallback: Claude SVG using concept description
        console.log(`Logo ${i+1}: fal failed, using Claude SVG`)
        const svg = await generateSVGLogo(anthropic, concept, colors, kit.business_name)
        logoUrls.push('')
        logoSvgs.push(svg)
        usedFal.push(false)
      }
    }

    const updatedVisual = {
      ...visual,
      logo_urls: logoUrls,
      logo_svgs: logoSvgs,
      logo_prompts: promptsUsed,
      logos_generated_at: new Date().toISOString(),
    }
    await adminClient.from('brand_kits').update({ visual_data: updatedVisual }).eq('id', brand_kit_id)

    return NextResponse.json({
      ok: true,
      count: logoUrls.filter(u => u).length + logoSvgs.filter(s => s).length,
      logo_urls: logoUrls,
      used_fal: usedFal,
    })
  } catch (err) {
    console.error('generate-logos error:', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
